---
title: "ANALIZANDO ESTIMADORES RESPECTO AL EMPLEO USANDO LA ENCUESTA HOGARES "
author: 
- "Integrantes: Leo ALejandro Chirirno - Alejandro Cardenas Soria - Sergio Colque"
date: "2023-06-07"
output: html_document
bibliography: Bib.bib
csl: apa.csl
---

\pagebreak

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## INTRODUCCI칍N.
Las encuestas de hogares por muestreo constituyen una manera pr치ctica de obtener datos actualizados sobre las condiciones y tendencias sociales, el comportamiento socioecon칩mico de los hogares, el acceso a los servicios b치sicos de bienestar y el efecto de los programas de bienestar.[@cepal1979medicion]

## OBJETIVOS
El objetivo del proyecto es conocer las principales caracteristicas de la situacion laboral a traves de la encuesta hogares usando indicadores.

## MOTIVACI칍N
La motivaci칩n para realizar este proyecto es exponer la realidad en cuanto a la oferta y demanda laboral que existe en el pa칤s.

## MARCO TE칍RICO 
El ingreso laboral es el conjunto de partidas monetarias y en especie percibidas en forma regular por los hogares como unidad o por sus integrantes a t칤tulo personal, a intervalos anuales o m치s frecuentes, excluyendo ganancias
inesperadas, irregulares o percibidas t칤picamente por una sola vez. [@brun2019medicion]
El ingreso laboral puede ser usado para elaborar indicadores como "La Tasa Global de Participacion" por nombrar alguno. El indicador es el dato num칠rico, resultado de un proceso que cuantifica cient칤ficamente una caracter칤stica de una muestra. [@sabalain2009introduccion]

## DESCRIPCI칍N DE LA BASE DE DATOS

- ylab: Ingreso laboral (Bs/Mes) (continua).
- desocupado: Poblaci칩n desocupada, medida booleana : 1 = s칤, 0 = no (discreta).
- depto: Medida que indica a que departamento de Bolivia pertence, esta medida va del 1 al 9 (discreta).
- pea: Poblacion Economicamente Activa, medida booleana : 1 = s칤, 0 = no (discreta).
- pet: Poblacion en edad de trabajar 14 o m치s a침os, medida booleana : 1 = s칤, 0 = no (discreta).
- pei: Poblacion Economicamente Inactiva, medida booleana : 1 = s칤, 0 = no (discreta).
- s01a_02: El sexo de la persona encuestada, 1 = Hombre, 2 = Mujer (discreta).
- s01a_03: Cuantos a침os cumplidos tiene la persona encuestada (discreta).

## METODOLOGIA

### 1. Indicadores y fichas de Indicadores

#### Tasa Global de Participaci칩n (TGP)

Definici칩n. Relaci칩n de la Poblaci칩n Econ칩micamente Activa (PEA) entre la Poblaci칩n en Edad de Trabajar (PET) que mide la proporci칩n de participaci칩n en el mercado laboral respecto al total de poblaci칩n que se encuentra en edad de trabajo. Poblaci칩n Econ칩micamente Activa (PEA) conjunto de personas de 14 a침os que, en la semana de referencia, estaban ocupadas o que estaban desocupadas, es decir, no estaban ocupadas, buscaban trabajo activamente y estaban disponibles para trabajar. Incluye tambi칠n, como ocupados, a quienes durante la semana de referencia estuvieron temporalmente ausentes de su empleo por razones circunstanciales.
M칠todo de c치lculo.
$$TGP_{\geq 14}=\dfrac{PEA_{\geq 14}}{PET_{\geq 14}}*100$$
Donde:

- $TGP_{\geq 14}$ = Tasa global de participaci칩n (para 14 o m치s a침os de edad)
- $PEA_{\geq 14}$= Poblaci칩n econ칩micamente activa (14 o m치s a침os de edad)
- $PET_{\geq 14}$= Poblaci칩n en edad de trabajar (14 o m치s a침os de edad)

#### Tasa de Desocupaci칩n (TD)

Definici칩n. Relaci칩n porcentual de la Poblaci칩n Desocupada de (PD) respecto a la Poblaci칩n Econ칩micamente Activa (PEA) que mide el desempe침o del mercado laboral y la econom칤a en su conjunto. Asimismo, mide la utilizaci칩n de la mano de obra en el mercado laboral y el fracaso de encontrar un trabajo. Poblaci칩n Desocupada (PD) son las personas de 14 a침os o m치s que, en la semana de referencia: no estaban ocupadas, llevaron a cabo actividades de b칰squeda de trabajo en las 칰ltimas cuatro (4) semanas y estaban disponibles para trabajar. Poblaci칩n Econ칩micamente Activa (PEA) conjunto de personas de 14 a침os que, en la semana de referencia, estaban ocupadas o que estaban desocupadas, es decir, no estaban ocupadas, buscaban trabajo activamente y estaban disponibles para trabajar. Incluye tambi칠n, como ocupados, a quienes durante la semana de referencia estuvieron temporalmente ausentes de su empleo por razones circunstanciales.
M칠todo de c치lculo.
$$TD_{\geq 14}=\dfrac{Desocupado_{\geq 14}}{PEA_{\geq 14}}*100$$
Donde:

- $TD_{\geq 14}$ = Tasa de desocupaci칩n (para 14 o m치s a침os de edad)
- $Desocupado_{\geq 14}$= Poblaci칩n Desocupada (14 o m치s a침os de edad) 
- $PEA_{\geq 14}$= Poblaci칩n econ칩micamente activa (14 o m치s a침os de edad)

#### Tasa de Ocupaci칩n (TO)

Definici칩n. Relaci칩n porcentual de la Poblaci칩n ocupada de (PA) respecto a la Poblaci칩n Econ칩micamente Activa (PEA) que mide el desempe침o del mercado laboral y la econom칤a en su conjunto. Poblaci칩n Ocupada (ocupado) son las personas de 14 a침os o m치s que, en la semana de referencia: estaban ocupadas, llevaron a cabo actividades de trabajo en las 칰ltimas cuatro (4) semanas . Poblaci칩n Econ칩micamente Activa (PEA) conjunto de personas de 14 a침os que, en la semana de referencia, estaban ocupadas o que estaban desocupadas, es decir, no estaban ocupadas, buscaban trabajo activamente y estaban disponibles para trabajar. Incluye tambi칠n, como ocupados, a quienes durante la semana de referencia estuvieron temporalmente ausentes de su empleo por razones circunstanciales.
M칠todo de c치lculo.
$$TO_{\geq 14}=\dfrac{Ocupado_{\geq 14}}{PEA_{\geq 14}}*100$$
Donde:

- $TO_{\geq 14}$ = Tasa de ocupaci칩n  (para 14 o m치s a침os de edad)
- $Ocupado_{\geq 14}$= Poblaci칩n ocupada (14 o m치s a침os de edad) 
- $PEA_{\geq 14}$= Poblaci칩n econ칩micamente activa (14 o m치s a침os de edad)

#### Tasa de Censat칤a (TC)

Definici칩n. Relaci칩n porcentual de la Poblaci칩n Cesante de (Censate) respecto a la Poblaci칩n Econ칩micamente Activa (PEA) que mide el desempe침o del mercado laboral y la econom칤a en su conjunto. Poblaci칩n Cesante (cesante) son las personas de 14 a침os o m치s que, son desocupados pero que han tenido un trabajo previamente como las que buscan trabajo por primera vez.. Poblaci칩n Econ칩micamente Activa (PEA) conjunto de personas de 14 a침os que, en la semana de referencia, estaban ocupadas o que estaban desocupadas, es decir, no estaban ocupadas, buscaban trabajo activamente y estaban disponibles para trabajar. Incluye tambi칠n, como ocupados, a quienes durante la semana de referencia estuvieron temporalmente ausentes de su empleo por razones circunstanciales.
M칠todo de c치lculo.
$$TC_{\geq 14}=\dfrac{Cesante_{\geq 14}}{PEA_{\geq 14}}*100$$
Donde:

- $TC_{\geq 14}$ = Tasa de cesant칤a (para 14 o m치s a침os de edad)
- $Cesante_{\geq 14}$= Poblaci칩n Cesante (14 o m치s a침os de edad) 
- $PEA_{\geq 14}$= Poblaci칩n econ칩micamente activa (14 o m치s a침os de edad)

#### Tasa de Aspirantes (TA)

Definici칩n. Relaci칩n porcentual de la Poblaci칩n Desocupada Aspirante (aspirante) respecto a la Poblaci칩n Econ칩micamente Activa (PEA) que mide el desempe침o del mercado laboral y la econom칤a en su conjunto. Poblaci칩n Desocupada Aspirante (aspirante) son las personas de 14 a침os o m치s que, en la semana de referencia: buscan trabajo por primera vez. Poblaci칩n Econ칩micamente Activa (PEA) conjunto de personas de 14 a침os que, en la semana de referencia, estaban ocupadas o que estaban desocupadas, es decir, no estaban ocupadas, buscaban trabajo activamente y estaban disponibles para trabajar. Incluye tambi칠n, como ocupados, a quienes durante la semana de referencia estuvieron temporalmente ausentes de su empleo por razones circunstanciales.
M칠todo de c치lculo.
$$TA_{\geq 14}=\dfrac{Aspiramente_{\geq 14}}{PEA_{\geq 14}}*100$$
Donde:

- $TA_{\geq 14}$ = Tasa de aspirantes (para 14 o m치s a침os de edad)
- $Cesante_{\geq 14}$= Poblaci칩n Desocupada Aspirante (14 o m치s a침os de edad) 
- $PEA_{\geq 14}$= Poblaci칩n econ칩micamente activa (14 o m치s a침os de edad)

#### Tasa de Inactividad (TI)

Definici칩n. Es el porcentaje de la poblaci칩n econ칩micamente inactiva (PEI) o no econ칩micamente activa, con respecto a la poblaci칩n en edad de trabajar (14 a침os y m치s), durante un determinado periodo. Se mide a trav칠s de la relaci칩n de la Poblaci칩n Econ칩micamente Inactiva (PEI) y la Poblaci칩n en Edad de Trabajar (PET). 
M칠todo de c치lculo.
$$TI_{\geq 14}=\dfrac{PEI_{\geq 14}}{PET_{\geq 14}}*100$$

Donde:

- $TI_{\geq 14}$ = Tasa global de inactividad (para 14 o m치s a침os de edad)
- $PEA_{\geq 14}$= Poblaci칩n econ칩micamente inactiva (14 o m치s a침os de edad)
- $PET_{\geq 14}$= Poblaci칩n en edad de trabajar (14 o m치s a침os de edad)

#### Indice de Carga Econ칩mica (ICE)

Definici칩n. Representa la carga econ칩mica que debe asimilar una persona econ칩micamente activa en favor de una persona econ칩micamente inactiva, es decir, la relaci칩n entre actividad y no actividad. Se mide a trav칠s de la relaci칩n de la Poblaci칩n Econ칩micamente Inactiva (PEI) y la Poblaci칩n Econ칩micamente Activa (PEA). Poblaci칩n Econ칩micamente inactiva (PEI) conjunto de personas con 14 a침os o m치s que al momento de la encuesta no han participado en el mercado laboral en la semana de referencia o, en otros t칠rminos, sin ocupaci칩n ni buscan activamente una ocupaci칩n. Poblaci칩n Econ칩micamente Activa (PEA) conjunto de personas de 14 a침os que, en la semana de referencia, estaban ocupadas o que estaban desocupadas, es decir, no estaban ocupadas, buscaban trabajo activamente y estaban disponibles para trabajar. Incluye tambi칠n, como ocupados, a quienes durante la semana de referencia estuvieron temporalmente ausentes de su empleo por razones circunstanciales.
M칠todo de c치lculo.
$$ICE_{\geq 14}=\dfrac{PEI_{\geq 14}}{PEA_{\geq 14}}*100$$
Donde:

- $ICE_{\geq 14}$= 칈ndice de Carga Econ칩mica (para 14 o m치s a침os de edad)
- $PEI_{\geq 14}$= Poblaci칩n econ칩micamente inactiva (14 o m치s a침os de edad) 
- $PEA_{\geq 14}$= Poblaci칩n econ칩micamente activa (14 o m치s a침os de edad)


### 2. Tratamiento sobre la base de datos
Se usar치 la base de datos de la Encuesta Hogares 2021 del 치rea de personas para poder obtener las variables necesarias y asi sacar los indicadores ya mencionados.
La base de datos tiene que ser filtrada para los encuestados que tienen 14 a침os o m치s. Adem치s que ser치 desagregada por departamentos, 치rea y sexo.

**EH2021_p %>% filter(s01a_03>=14) %>% group_by(depto)**

**No se utilizo el dise絪 muestral**

### 3. Visualizacion de la informaci칩n
Se utilizo la libreria "ggplot2" para la realizacion de los graficos.

Los graficos y las tablas se encuentran en el dashboard.

### 4. Armado de la plataforma

Se uso las librerias shiny y shinydashboard para el armado de la plataforma.

## Concluciones y recomendaciones 



## Referencias